---
abstract: 'Fast JSON module for Kelp'
author:
  - 'Stefan Geneshky <minimal@cpan.org>'
build_requires:
  HTTP::Request::Common: '0'
  Kelp: '0'
  Kelp::Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Kelp-Module-JSON-XS
requires:
  Carp: '0'
  JSON::XS: '0'
  Kelp::Base: '0'
resources:
  homepage: https://github.com/naturalist/kelp-module-json-xs
  repository: https://github.com/naturalist/kelp-module-json-xs.git
version: '0.502'
